### PR TITLE
Search armory

### PR DESCRIPTION
**Pull request by cranberyxl**

### CODE REVIEW

**Comment by cmacrae** [comment]
:+1:  This'd be nice

**Comment by cprater** [comment]
Been meaning too look at this for a while @cranberyxl Can you make your PR against this repository directly instead of from a fork please?

**Comment by cranberyxl** [comment]
@cprater Not sure what you mean

**Comment by cprater** [comment]
@cranberyxl It looks like this pull request is from a repository you might have forked, which makes it hard for me to test in my slack channel. If you could make the code changes against this repo, it would be easier for me to test them out.

**Comment by cranberyxl** [comment]
I can't make branches in your repo unless I'm a contributor. Github uses forks to address this. You can clone my repo if you want to test it.

**Comment by cprater** [comment]
Ahh duh, that makes sense thanks for the insight. Ill check it out soon, hopefully today. It looks good I just want to see it work with my own eyes

**Comment by cprater** [comment]
Its embarrassing how long this took me, and for that I am sorry

**Pull request merged**
